.PHONY: clean All

All:
	@echo "----------Building project:[ FuckIfIKnow - Debug ]----------"
	@cd "FuckIfIKnow" && "$(MAKE)" -f  "FuckIfIKnow.mk"
clean:
	@echo "----------Cleaning project:[ FuckIfIKnow - Debug ]----------"
	@cd "FuckIfIKnow" && "$(MAKE)" -f  "FuckIfIKnow.mk" clean
